apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.name }}
  labels:
    name: prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image }}
          ports:
            - containerPort: 8080
          env:
{{- range .Values.vars }}
            - name: {{ .varName }}
              value: {{ .varValue }}
{{- end }}


---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 # Updated to match the containerPort

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}-ingress
spec:
  rules:
    - host: finance-tracker.harness-demo.site
      http:
        paths:
          - path: /api # Updated to route /callback to your service
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.name }}
                port:
                  number: 80
